name: sm_input_field
description: a package to create input fields in a simple manner, facilitates the easy and simple creation of beautiful forms too
version: 1.4.0
homepage: https://github.com/Saleh-Marji/sm_input_field.git

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
